#!/data/data/com.termux/files/usr/bin/bash
echo "Open Home OS v13.5 RTSP Camera Setup - Instalando..."
BASE="$HOME/OpenHomeOS"; WEB="$BASE/Web"; CONFIG="$BASE/Config"; DATA="$BASE/Data"
mkdir -p "$WEB" "$CONFIG" "$BASE/Logs" "$DATA/Files" "$DATA/Cameras" "$DATA/Snapshots" "$DATA/Backups" "$DATA/IoT" "$DATA/Connect" "$DATA/Network" "$DATA/Discovery"
[ -f "$CONFIG/devices.json" ] || echo "[]" > "$CONFIG/devices.json"
[ -f "$CONFIG/rooms.json" ] || echo '["Sala","Quarto","Cozinha","Garagem","Oficina","Jardim"]' > "$CONFIG/rooms.json"
[ -f "$CONFIG/network_devices.json" ] || echo '{"last_scan":"","devices":[],"summary":{},"count":0}' > "$CONFIG/network_devices.json"
[ -f "$CONFIG/discovery_state.json" ] || echo '{"running":false,"progress":0,"message":"Aguardando busca.","last_scan":"","devices":[],"summary":{},"count":0}' > "$CONFIG/discovery_state.json"
[ -f "$CONFIG/tuya_cloud.json" ] || echo '{"enabled":false,"client_id":"","client_secret":"","data_center":"https://openapi.tuyaus.com","asset_id":"","last_sync":"","token":"","token_expire":0}' > "$CONFIG/tuya_cloud.json"
cp -f public/index.html "$WEB/index.html"
cp -rf public/css "$WEB/"
cp -rf public/js "$WEB/"
bash scripts/config_nginx.sh
command -v ffprobe >/dev/null 2>&1 || echo "ATENÇÃO: instale o testador RTSP com: pkg install ffmpeg"
echo "Instalação concluída. Rode: nginx -s reload && bash scripts/start_api.sh"
