#!/data/data/com.termux/files/usr/bin/bash
echo "LG Home Server v4 - Diagnóstico"
echo "-------------------------------"
echo "Pasta atual: $(pwd)"
echo "Home: $HOME"
echo ""
echo "Projeto:"
ls
echo ""
echo "Scripts:"
ls scripts 2>/dev/null || echo "scripts não encontrada"
echo ""
echo "Web:"
ls "$HOME/Servidor/Web" 2>/dev/null || echo "Web não encontrada"
echo ""
echo "Nginx:"
pgrep nginx >/dev/null && echo "Ativo" || echo "Parado"
echo ""
echo "API:"
pgrep -f "api/server.py" >/dev/null && echo "Ativa" || echo "Parada"
echo ""
echo "IP:"
ip -o -4 addr show 2>/dev/null | awk '!/127.0.0.1/ {print $2, $4}'
